### ISSUE TITLE
Feedback related to Project 1 (Team Neo)

### ISSUE THREAD

**Issue by rajdeepc2792** [airavata-courses/garuda#68]
Congratulations on coming up with a smooth UI and data flow.

UI seems very minimal and intuitive.
Below is the resultant data:-

<img width="1116" alt="Screen Shot 2022-02-09 at 4 49 31 PM" src="https://user-images.githubusercontent.com/16707567/153296153-eccb5b8f-c63f-4d33-b9d1-face514e3b11.png">

There are some points I will which we want to bring to your knowledge:-

- You tried well to persist the data to db for any search before returning it to the user. But It seems some of the time durations have huge data that it's not getting retrieved properly because of the MongoDB limitations. Maybe you can compress the lat-long data to already compressed data and then store to DB. So that merging documents won't reach the limit.
- Docker Images can be reduced in size using alpine os images of Node, python and Java(Not sure about this)
- Build time can be removed by pushing images on Docker Hub

Review Done by Team Neo(https://github.com/airavata-courses/neo)

**Comment by pranavacharya** [comment]
Thanks for your review !

1. Yes, thanks for reporting bug caused by large data set. We have opened an issue #71 
2. Planning to include docker hub in out next sprint
