### ISSUE TITLE
Project 1 Feedback (Scapsulators)

### ISSUE THREAD

**Issue by shubhpatr** [airavata-courses/garuda#70]
Just ran your project, and I have a couple of comments and suggestions - 

Build time took around 12-14 minutes, was easy to follow from the readme files. 

1) Implementation of CircleCI for continous builds on commits
2) Using docker-hub instead of individually building each microservice in your main repo
3) Time slot selection doesn't seem so intuitive at all
4) Could've explored more properties instead of just reflectivity
5) Also not sure how you're handling the error when there's no data for the querry

Rest great work! Loved your project as such

Reviewed by Team Scapsulators (https://github.com/airavata-courses/scapsulators)

**Comment by rishi1596** [comment]
Thanks @shubhpatr much appreciated.
We would try to cover the mentioned points in the next sprint.
