### ISSUE TITLE
render map and plot data in react UI

### ISSUE THREAD

**Issue by rishi1596** [airavata-courses/garuda#9]

**Comment by rishi1596** [comment]
@pranavacharya please pick this task after your current pull request is completed.

**Comment by pranavacharya** [comment]
Sure, once I finish conversion of distance, azimuth to latitude and longitude feature, I'll pick this

**Comment by pranavacharya** [comment]
@rishi1596 @tanmaysawaji I tried implementing map rendering feature using leaflet,  I feel that tiles of openstreet map are loading slowly. I am now trying to make use of react-simple-map since we only need country and state outline.

**Comment by rishi1596** [comment]
Okay. Please read the details about it before implementing it.

**Comment by rishi1596** [comment]
Merged in the main branch.
Closing the issue.
